#!/usr/bin/env bash

. ./util/common.sh

function main() {
  local debugger="${TOOLCHAIN}/bin/i586-elf-gdb"
  local serial="tail -f serial.out | ./util/colorize.sh"
  local emulator="qemu-system-i386 -s -S -serial file:serial.out -monitor stdio"

  emulator="${emulator} -hda image.img"
  emulator="${emulator} -vnc :5500,reverse"

  tmux new-window -n "emul" "${emulator}; tmux kill-window -t emul"
  tmux split-window -dh -t emul.0 "sleep 1; ${debugger} 2>output.log"
  tmux split-window -dv -t emul.0 "${serial}"
}

main "${@}"
