#!/usr/bin/env bash
#
# Requires a gcc cross compile in order to build
# Proposed build instructions in gcc source directory
#
# > configure --target=i386-elf --prefix=/usr/local/Cellar/gcc-cross/<version>
# > make all-gcc
# > make install-gcc
# > brew link gcc-cross
#
# Also requires specially build binutils.

BUILDDIR=`pwd`/build
NEWLIBDIR=`pwd`/newlib

LDPATH=`which i386-elf-ld`
LDDIR=`dirname $LDPATH`
LDREAL=`readlink $LDPATH`
LDREALDIR=`dirname $LDREAL`
BINUTILS=`cd $LDDIR/$LDREALDIR/../i386-elf/bin; pwd`

pushd $BUILDDIR/newlib
  if [ $1 == "all" ]; then
    rm -r *
    $NEWLIBDIR/configure --prefix=$BUILDDIR/lib --target=i386-elf
  fi
  export PATH=$BINUTILS:$PATH
  make all
  make install
  cp /usr/local/Cellar/gcc-cross/4.8.1/lib/gcc/i386-elf/4.8.1/include/stddef.h $BUILDDIR/lib/i386-elf/include/.
popd
